name: Frontend CD

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1ubilemcj7s73ec6f8g?key=W72S759OBLA
